dependencies:
- name: croc-hunter-jenkinsx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.69
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: go-demo-6
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.379
- name: jx-go
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: jx-prow
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: tmx-bji
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
